In [38]:
from pandas import DataFrame, read_csv
from numpy import random, arange

In [26]:
base = {
    'ids': arange(1, 1001),
    'idades': random.randint(18, 80, size=1000),
    'sexos': random.choice(['M', 'F'], size=1000),
    'estados_civis': random.choice(['Solteiro(a)', 'Casado(a)', 'Solteiro(a)', 'Divorciado(a)', 'Solteiro(a)'],1000),
    'sinistros': random.randint(0, 5, 1000),
    'premios': random.gamma(2, 1000, size=1000)
}

In [39]:
base = DataFrame(base)
base.head()

   ids  idades sexos  estados_civis  sinistros      premios
0    1      58     F      Casado(a)          3  2873.078718
1    2      71     F      Casado(a)          2  2606.123705
2    3      33     M    Solteiro(a)          3   839.817127
3    4      70     M    Solteiro(a)          4   922.505137
4    5      38     F  Divorciado(a)          2  1007.038732

In [41]:
clientes_maior_30anos = base[base['idades'] > 30]
clientes_maior_30anos

      ids  idades sexos  estados_civis  sinistros      premios
0       1      58     F      Casado(a)          3  2873.078718
1       2      71     F      Casado(a)          2  2606.123705
2       3      33     M    Solteiro(a)          3   839.817127
3       4      70     M    Solteiro(a)          4   922.505137
4       5      38     F  Divorciado(a)          2  1007.038732
..    ...     ...   ...            ...        ...          ...
993   994      42     M      Casado(a)          0  1082.026174
994   995      34     F  Divorciado(a)          0  3029.367299
995   996      70     F    Solteiro(a)          1  1281.203814
997   998      62     F      Casado(a)          2  1717.442196
999  1000      74     F      Casado(a)          1   911.179913

[793 rows x 6 columns]

In [42]:
clientes_sem_sinistro = base.query('sinistros == 0')
clientes_sem_sinistro

     ids  idades sexos  estados_civis  sinistros      premios
6      7      39     M    Solteiro(a)          0  3682.045241
8      9      62     M      Casado(a)          0  2747.273750
15    16      19     M    Solteiro(a)          0  1886.324770
16    17      45     F    Solteiro(a)          0  2908.600758
19    20      75     F  Divorciado(a)          0    69.791005
..   ...     ...   ...            ...        ...          ...
980  981      32     M    Solteiro(a)          0  1456.470729
983  984      22     F  Divorciado(a)          0  1831.994133
986  987      61     M      Casado(a)          0  3085.796277
993  994      42     M      Casado(a)          0  1082.026174
994  995      34     F  Divorciado(a)          0  3029.367299

[211 rows x 6 columns]

In [55]:
for linha, coluna in base.iterrows():
    print(f"Idade: {coluna['idades']}, PrÃªmio: {coluna['premios']}")

Idade: 58, PrÃªmio: 2873.0787175595733
Idade: 71, PrÃªmio: 2606.123704673479
Idade: 33, PrÃªmio: 839.8171266380926
Idade: 70, PrÃªmio: 922.5051367953209
Idade: 38, PrÃªmio: 1007.0387321129955
Idade: 50, PrÃªmio: 1001.4949776076683
Idade: 39, PrÃªmio: 3682.045240969325
Idade: 76, PrÃªmio: 1446.5072860939042
Idade: 62, PrÃªmio: 2747.273749705104
Idade: 76, PrÃªmio: 1196.1622337813137
Idade: 32, PrÃªmio: 491.58974040400005
Idade: 64, PrÃªmio: 1452.5819858101934
Idade: 19, PrÃªmio: 551.1294267675656
Idade: 23, PrÃªmio: 1085.1903992230157
Idade: 49, PrÃªmio: 1130.4510627327213
Idade: 19, PrÃªmio: 1886.3247696670387
Idade: 45, PrÃªmio: 2908.6007578903973
Idade: 58, PrÃªmio: 5542.578565451634
Idade: 52, PrÃªmio: 3792.1556167020995
Idade: 75, PrÃªmio: 69.79100451039983
Idade: 63, PrÃªmio: 1024.8250089059572
Idade: 28, PrÃªmio: 2088.411289611302
Idade: 79, PrÃªmio: 3311.2218527650653
Idade: 52, PrÃªmio: 2424.527480358891
Idade: 56, PrÃªmio: 1412.6430015837075
Idade: 51, PrÃªmio: 2877.327980165459
Idade: 40, PrÃªmio: 2409.3790584953194
Idade: 40, PrÃªmio: 1315.827410702624
Idade: 30, PrÃªmio: 499.26176436649484
Idade: 43, PrÃªmio: 2433.155873383419
Idade: 43, PrÃªmio: 1385.7375852471034
Idade: 71, PrÃªmio: 537.9196847505317
Idade: 71, PrÃªmio: 504.226667978416
Idade: 29, PrÃªmio: 3323.0862945720646
Idade: 59, PrÃªmio: 2692.319777740767
Idade: 48, PrÃªmio: 1089.8383069539866
Idade: 29, PrÃªmio: 954.8196453879436
Idade: 55, PrÃªmio: 1115.9218077217945
Idade: 50, PrÃªmio: 49.16805401200686
Idade: 42, PrÃªmio: 872.1648061809209
Idade: 22, PrÃªmio: 692.2264333747606
Idade: 59, PrÃªmio: 1357.82850595334
Idade: 36, PrÃªmio: 1863.3218038681732
Idade: 51, PrÃªmio: 2238.563761558516
Idade: 19, PrÃªmio: 1259.8819541958217
Idade: 56, PrÃªmio: 24.27514897905428
Idade: 62, PrÃªmio: 2530.28946931624
Idade: 48, PrÃªmio: 1458.3196510805396
Idade: 54, PrÃªmio: 1143.6335910755056
Idade: 33, PrÃªmio: 4836.8977254174015
Idade: 38, PrÃªmio: 2151.3715170049336
Idade: 34, PrÃªmio: 2509.1568686033743
Idade: 31, PrÃªmio: 1063.5719084125903
Idade: 44, PrÃªmio: 657.3153338175408
Idade: 48, PrÃªmio: 736.1525853318728
Idade: 37, PrÃªmio: 4690.756069280752
Idade: 33, PrÃªmio: 1369.710284265668
Idade: 70, PrÃªmio: 1055.4851668540382
Idade: 57, PrÃªmio: 843.5311999010517
Idade: 29, PrÃªmio: 755.4827569806608
Idade: 20, PrÃªmio: 1950.7059933139626
Idade: 78, PrÃªmio: 552.1878912122706
Idade: 22, PrÃªmio: 2749.5897485519986
Idade: 74, PrÃªmio: 274.03144322354507
Idade: 79, PrÃªmio: 1028.471973056219
Idade: 49, PrÃªmio: 394.79245455826754
Idade: 53, PrÃªmio: 3534.762899014878
Idade: 57, PrÃªmio: 1943.7130317246329
Idade: 77, PrÃªmio: 682.7993461374125
Idade: 67, PrÃªmio: 2199.3362095466696
Idade: 21, PrÃªmio: 4571.52675327777
Idade: 26, PrÃªmio: 1746.9901015927219
Idade: 50, PrÃªmio: 2561.420993938941
Idade: 70, PrÃªmio: 642.8650661964422
Idade: 66, PrÃªmio: 6683.181338380648
Idade: 72, PrÃªmio: 2071.198559400109
Idade: 28, PrÃªmio: 953.4445358921668
Idade: 58, PrÃªmio: 3134.2480904170793
Idade: 22, PrÃªmio: 1562.476105052165
Idade: 75, PrÃªmio: 911.8060606938552
Idade: 21, PrÃªmio: 1201.2613657992697
Idade: 77, PrÃªmio: 644.2462711167989
Idade: 45, PrÃªmio: 1639.9102834544744
Idade: 39, PrÃªmio: 1981.3551903100276
Idade: 24, PrÃªmio: 3174.165035049545
Idade: 31, PrÃªmio: 4228.900704961612
Idade: 33, PrÃªmio: 3038.1048393885508
Idade: 62, PrÃªmio: 6422.852307683274
Idade: 44, PrÃªmio: 3052.735975159277
Idade: 71, PrÃªmio: 3334.9296787754542
Idade: 52, PrÃªmio: 4366.804953258027
Idade: 47, PrÃªmio: 1286.3118556421132
Idade: 60, PrÃªmio: 3639.397144288603
Idade: 43, PrÃªmio: 3505.1916617098586
Idade: 78, PrÃªmio: 1744.7885430437016
Idade: 20, PrÃªmio: 1704.3262388595313
Idade: 26, PrÃªmio: 1621.6440423855854
Idade: 58, PrÃªmio: 2581.610197964864
Idade: 43, PrÃªmio: 2427.3249736022876
Idade: 27, PrÃªmio: 5928.563140727039
Idade: 50, PrÃªmio: 238.19015045444348
Idade: 26, PrÃªmio: 2941.047742823042
Idade: 48, PrÃªmio: 4091.682819039597
Idade: 29, PrÃªmio: 2407.9183421743664
Idade: 39, PrÃªmio: 2720.2504538219005
Idade: 43, PrÃªmio: 2714.844832130878
Idade: 33, PrÃªmio: 838.2303209879603
Idade: 37, PrÃªmio: 3538.781360703128
Idade: 51, PrÃªmio: 555.5433418296869
Idade: 19, PrÃªmio: 167.07273221667532
Idade: 51, PrÃªmio: 3609.6457791336907
Idade: 56, PrÃªmio: 5508.49258285187
Idade: 23, PrÃªmio: 2339.7441421345834
Idade: 20, PrÃªmio: 1535.7901078016787
Idade: 23, PrÃªmio: 1454.9641745082804
Idade: 78, PrÃªmio: 2782.900930738807
Idade: 27, PrÃªmio: 885.1268796442057
Idade: 72, PrÃªmio: 342.1380112602007
Idade: 66, PrÃªmio: 4144.762051728096
Idade: 47, PrÃªmio: 1373.8968772171477
Idade: 40, PrÃªmio: 2210.150114394431
Idade: 26, PrÃªmio: 2120.758257611488
Idade: 21, PrÃªmio: 2288.2027542784685
Idade: 61, PrÃªmio: 293.745995869972
Idade: 51, PrÃªmio: 2124.78377947833
Idade: 26, PrÃªmio: 6411.05712899293
Idade: 50, PrÃªmio: 1617.8473427020815
Idade: 37, PrÃªmio: 4145.234402032842
Idade: 41, PrÃªmio: 3614.2676864928144
Idade: 20, PrÃªmio: 3325.0051589103214
Idade: 36, PrÃªmio: 2434.830660648237
Idade: 78, PrÃªmio: 2830.1454072400543
Idade: 53, PrÃªmio: 1504.78723844597
Idade: 46, PrÃªmio: 1709.5326065042414
Idade: 38, PrÃªmio: 3615.5640826742224
Idade: 42, PrÃªmio: 1594.823389483132
Idade: 48, PrÃªmio: 2911.8795834916546
Idade: 46, PrÃªmio: 2859.7038516112043
Idade: 72, PrÃªmio: 1151.5700631506388
Idade: 18, PrÃªmio: 639.1838072996485
Idade: 58, PrÃªmio: 2530.3594154852626
Idade: 56, PrÃªmio: 1526.448620960545
Idade: 44, PrÃªmio: 2157.5199964710196
Idade: 36, PrÃªmio: 1097.0642241589926
Idade: 23, PrÃªmio: 640.855971261045
Idade: 48, PrÃªmio: 133.2533535808088
Idade: 21, PrÃªmio: 2819.152525230616
Idade: 39, PrÃªmio: 4663.789821357751
Idade: 26, PrÃªmio: 1659.5677999738218
Idade: 64, PrÃªmio: 1352.622717429426
Idade: 29, PrÃªmio: 1467.984941201089
Idade: 65, PrÃªmio: 4863.416467790663
Idade: 53, PrÃªmio: 1507.5342004377228
Idade: 76, PrÃªmio: 1545.9373426960901
Idade: 31, PrÃªmio: 4523.986773477929
Idade: 59, PrÃªmio: 2409.7140148889766
Idade: 20, PrÃªmio: 1313.6914751839577
Idade: 69, PrÃªmio: 3120.252135908309
Idade: 20, PrÃªmio: 1850.5489541964978
Idade: 58, PrÃªmio: 1715.8692451082284
Idade: 60, PrÃªmio: 1307.8332826797443
Idade: 34, PrÃªmio: 2307.063867742509
Idade: 38, PrÃªmio: 1440.1566765684026
Idade: 37, PrÃªmio: 768.621536063997
Idade: 57, PrÃªmio: 4084.2004190595994
Idade: 69, PrÃªmio: 1251.293857183022
Idade: 71, PrÃªmio: 2414.571983039461
Idade: 36, PrÃªmio: 1634.2294925827057
Idade: 28, PrÃªmio: 2212.1822208046015
Idade: 34, PrÃªmio: 1503.0884242280238
Idade: 19, PrÃªmio: 1050.873702449927
Idade: 20, PrÃªmio: 1450.4385108884985
Idade: 72, PrÃªmio: 2001.2854880922907
Idade: 66, PrÃªmio: 3199.9622466941228
Idade: 55, PrÃªmio: 3418.201522271562
Idade: 33, PrÃªmio: 2009.305576005777
Idade: 21, PrÃªmio: 763.3873051313244
Idade: 70, PrÃªmio: 4815.326410548247
Idade: 75, PrÃªmio: 4923.591915833531
Idade: 73, PrÃªmio: 2025.5394026371985
Idade: 60, PrÃªmio: 2268.2256210294654
Idade: 77, PrÃªmio: 1547.4191151464065
Idade: 43, PrÃªmio: 533.0127773232894
Idade: 59, PrÃªmio: 218.03270975956056
Idade: 75, PrÃªmio: 2352.231431943
Idade: 44, PrÃªmio: 2195.8690177666913
Idade: 21, PrÃªmio: 1927.7160824744574
Idade: 69, PrÃªmio: 1202.5093034639317
Idade: 26, PrÃªmio: 4739.086003530735
Idade: 44, PrÃªmio: 4010.8997072391385
Idade: 47, PrÃªmio: 851.0854570571843
Idade: 51, PrÃªmio: 1664.0896631009737
Idade: 79, PrÃªmio: 1654.6086697292192
Idade: 63, PrÃªmio: 625.1180450197725
Idade: 45, PrÃªmio: 358.3661692062151
Idade: 45, PrÃªmio: 2170.901859126186
Idade: 34, PrÃªmio: 642.7750473002632
Idade: 25, PrÃªmio: 2297.347721254475
Idade: 60, PrÃªmio: 601.4220844847289
Idade: 79, PrÃªmio: 1356.3602451202178
Idade: 39, PrÃªmio: 1608.5431828763183
Idade: 36, PrÃªmio: 1955.0954539444208
Idade: 57, PrÃªmio: 2191.145000984476
Idade: 61, PrÃªmio: 402.08613401960963
Idade: 58, PrÃªmio: 325.9961629248765
Idade: 48, PrÃªmio: 2063.7794686012076
Idade: 54, PrÃªmio: 2984.966327209868
Idade: 44, PrÃªmio: 3288.467097499523
Idade: 59, PrÃªmio: 2264.894279889498
Idade: 43, PrÃªmio: 1215.0475573232618
Idade: 49, PrÃªmio: 790.9673953449276
Idade: 72, PrÃªmio: 2835.049842196134
Idade: 71, PrÃªmio: 484.5438114374551
Idade: 41, PrÃªmio: 1650.4541633827273
Idade: 36, PrÃªmio: 4255.253994357115
Idade: 27, PrÃªmio: 5859.889982367897
Idade: 58, PrÃªmio: 1653.128597959476
Idade: 55, PrÃªmio: 177.51501683170588
Idade: 39, PrÃªmio: 3395.9623481028366
Idade: 45, PrÃªmio: 773.944939681325
Idade: 62, PrÃªmio: 1149.7457803779319
Idade: 57, PrÃªmio: 1498.5506103543596
Idade: 35, PrÃªmio: 947.3874907362217
Idade: 47, PrÃªmio: 3991.388022604675
Idade: 64, PrÃªmio: 3066.123466825528
Idade: 22, PrÃªmio: 2036.3747571446606
Idade: 64, PrÃªmio: 726.0852339666676
Idade: 59, PrÃªmio: 857.6721242173779
Idade: 64, PrÃªmio: 3350.7007795352915
Idade: 79, PrÃªmio: 571.5078563281143
Idade: 70, PrÃªmio: 1625.7701675294886
Idade: 52, PrÃªmio: 543.5819733558627
Idade: 34, PrÃªmio: 7346.673637149842
Idade: 74, PrÃªmio: 860.7100809861549
Idade: 37, PrÃªmio: 531.2306730905003
Idade: 68, PrÃªmio: 1310.7087451511793
Idade: 33, PrÃªmio: 959.588436334035
Idade: 48, PrÃªmio: 750.0735869885582
Idade: 57, PrÃªmio: 2136.728029636312
Idade: 39, PrÃªmio: 3400.4753210410254
Idade: 58, PrÃªmio: 1921.1995728885634
Idade: 22, PrÃªmio: 1101.4432723308782
Idade: 66, PrÃªmio: 3263.8999730516184
Idade: 67, PrÃªmio: 3891.198582960725
Idade: 54, PrÃªmio: 491.08999683116963
Idade: 27, PrÃªmio: 3682.7253166328564
Idade: 40, PrÃªmio: 909.7056673929164
Idade: 25, PrÃªmio: 1568.5914889478322
Idade: 35, PrÃªmio: 1383.5185160124545
Idade: 64, PrÃªmio: 463.07693569682294
Idade: 43, PrÃªmio: 804.0567471284498
Idade: 79, PrÃªmio: 1149.5970733054883
Idade: 27, PrÃªmio: 1768.466735569231
Idade: 79, PrÃªmio: 2212.0665601952965
Idade: 30, PrÃªmio: 634.947481952725
Idade: 51, PrÃªmio: 2558.433719452912
Idade: 74, PrÃªmio: 868.7173889899784
Idade: 46, PrÃªmio: 1290.651332975556
Idade: 70, PrÃªmio: 938.3960952442022
Idade: 64, PrÃªmio: 755.3949669162512
Idade: 63, PrÃªmio: 2474.0449652227303
Idade: 21, PrÃªmio: 2469.1074086562057
Idade: 51, PrÃªmio: 2100.6378552843016
Idade: 61, PrÃªmio: 1688.834628311666
Idade: 68, PrÃªmio: 4259.317042600151
Idade: 40, PrÃªmio: 2337.121266965953
Idade: 45, PrÃªmio: 1172.6676246071438
Idade: 21, PrÃªmio: 3643.032738864008
Idade: 68, PrÃªmio: 711.413820411498
Idade: 55, PrÃªmio: 2334.1775109407854
Idade: 36, PrÃªmio: 1234.9297794214685
Idade: 52, PrÃªmio: 3134.0661013735394
Idade: 18, PrÃªmio: 3737.011341340286
Idade: 73, PrÃªmio: 1835.6074803803845
Idade: 48, PrÃªmio: 4013.7893496943234
Idade: 77, PrÃªmio: 727.9891429991376
Idade: 53, PrÃªmio: 1179.5807880090338
Idade: 39, PrÃªmio: 1695.2083684471768
Idade: 18, PrÃªmio: 1903.6436387665342
Idade: 43, PrÃªmio: 1416.3652865345725
Idade: 46, PrÃªmio: 4474.802770078628
Idade: 53, PrÃªmio: 1136.0568939375657
Idade: 54, PrÃªmio: 491.52104137964255
Idade: 44, PrÃªmio: 1499.249195875869
Idade: 38, PrÃªmio: 623.7716167833323
Idade: 30, PrÃªmio: 616.061684302322
Idade: 32, PrÃªmio: 3336.3684334485956
Idade: 43, PrÃªmio: 4844.688766794907
Idade: 18, PrÃªmio: 2113.805083320503
Idade: 19, PrÃªmio: 3523.6973735359297
Idade: 25, PrÃªmio: 596.673320725533
Idade: 22, PrÃªmio: 464.399193329356
Idade: 35, PrÃªmio: 1035.6832322720963
Idade: 24, PrÃªmio: 3237.8166833388495
Idade: 37, PrÃªmio: 1375.490201034722
Idade: 46, PrÃªmio: 2352.312715066037
Idade: 60, PrÃªmio: 1564.9470299515972
Idade: 39, PrÃªmio: 1521.2790751889129
Idade: 71, PrÃªmio: 3625.6366986571907
Idade: 19, PrÃªmio: 4709.731973577279
Idade: 69, PrÃªmio: 4318.160155340191
Idade: 28, PrÃªmio: 552.7155019244286
Idade: 68, PrÃªmio: 419.71938983708657
Idade: 34, PrÃªmio: 2599.218447246595
Idade: 42, PrÃªmio: 489.90001439179304
Idade: 18, PrÃªmio: 2881.2779964711426
Idade: 50, PrÃªmio: 454.93727048534885
Idade: 28, PrÃªmio: 638.3744509626562
Idade: 24, PrÃªmio: 706.5226044082476
Idade: 55, PrÃªmio: 3299.9695751246372
Idade: 79, PrÃªmio: 1208.8338448638708
Idade: 71, PrÃªmio: 956.3946096338409
Idade: 43, PrÃªmio: 1369.321518286209
Idade: 73, PrÃªmio: 117.12193968393892
Idade: 48, PrÃªmio: 3583.2673872563355
Idade: 34, PrÃªmio: 1698.8310354369812
Idade: 78, PrÃªmio: 202.88534451590246
Idade: 39, PrÃªmio: 3718.0039218181205
Idade: 54, PrÃªmio: 884.1512682350422
Idade: 36, PrÃªmio: 3203.128014085817
Idade: 33, PrÃªmio: 2015.117592598588
Idade: 70, PrÃªmio: 3297.9944683022627
Idade: 56, PrÃªmio: 2015.0899070453963
Idade: 35, PrÃªmio: 363.43559695086685
Idade: 41, PrÃªmio: 1019.3989076075607
Idade: 65, PrÃªmio: 573.5323940906321
Idade: 45, PrÃªmio: 1133.6502757844223
Idade: 21, PrÃªmio: 2565.5445582036136
Idade: 34, PrÃªmio: 1053.469074030677
Idade: 37, PrÃªmio: 4068.541649849906
Idade: 77, PrÃªmio: 1322.7889615860704
Idade: 31, PrÃªmio: 1469.0899786272043
Idade: 35, PrÃªmio: 1865.0874947997197
Idade: 49, PrÃªmio: 2522.223050376441
Idade: 48, PrÃªmio: 6402.49243705224
Idade: 35, PrÃªmio: 1645.4587568835702
Idade: 78, PrÃªmio: 519.7589640779285
Idade: 32, PrÃªmio: 1852.1745130568029
Idade: 26, PrÃªmio: 3843.0962145333438
Idade: 32, PrÃªmio: 1737.8248796505325
Idade: 75, PrÃªmio: 1731.701311771928
Idade: 43, PrÃªmio: 571.8707314157314
Idade: 44, PrÃªmio: 885.5851604212866
Idade: 79, PrÃªmio: 1130.904121233403
Idade: 27, PrÃªmio: 3114.6027072729967
Idade: 18, PrÃªmio: 757.719621222917
Idade: 44, PrÃªmio: 350.33285123146504
Idade: 25, PrÃªmio: 2174.0304169738074
Idade: 37, PrÃªmio: 3612.237430745899
Idade: 34, PrÃªmio: 4735.886378145902
Idade: 45, PrÃªmio: 2677.309697525033
Idade: 52, PrÃªmio: 1704.9776856408482
Idade: 20, PrÃªmio: 1609.442916962824
Idade: 26, PrÃªmio: 3343.8694131480715
Idade: 45, PrÃªmio: 2848.1416982298924
Idade: 37, PrÃªmio: 444.95199749541825
Idade: 68, PrÃªmio: 4246.669990518731
Idade: 58, PrÃªmio: 1588.938734587827
Idade: 38, PrÃªmio: 1238.8381092496768
Idade: 47, PrÃªmio: 2026.560091589257
Idade: 20, PrÃªmio: 1247.8820600910005
Idade: 63, PrÃªmio: 5072.250678659795
Idade: 51, PrÃªmio: 4123.82846483825
Idade: 65, PrÃªmio: 841.9348860124555
Idade: 48, PrÃªmio: 2299.614089522705
Idade: 67, PrÃªmio: 2330.0330248448495
Idade: 30, PrÃªmio: 1554.5770362424414
Idade: 70, PrÃªmio: 4943.4042720617035
Idade: 73, PrÃªmio: 2705.2185248921674
Idade: 22, PrÃªmio: 579.8727527178007
Idade: 32, PrÃªmio: 957.803065126352
Idade: 30, PrÃªmio: 3532.8992607551577
Idade: 23, PrÃªmio: 3767.0806964493477
Idade: 46, PrÃªmio: 2564.930028113421
Idade: 51, PrÃªmio: 658.0409483351604
Idade: 29, PrÃªmio: 2370.6302455985256
Idade: 78, PrÃªmio: 2066.7960280447214
Idade: 75, PrÃªmio: 4933.149447042321
Idade: 36, PrÃªmio: 2203.9568215878244
Idade: 44, PrÃªmio: 2948.1441173897556
Idade: 33, PrÃªmio: 2581.1218493520023
Idade: 22, PrÃªmio: 1588.8312611132608
Idade: 64, PrÃªmio: 2153.484076770007
Idade: 35, PrÃªmio: 99.74519571744217
Idade: 69, PrÃªmio: 1493.0415465639967
Idade: 78, PrÃªmio: 2827.9907015269464
Idade: 70, PrÃªmio: 1186.1074227171484
Idade: 24, PrÃªmio: 632.5559271004099
Idade: 58, PrÃªmio: 948.1271573871975
Idade: 23, PrÃªmio: 2934.020099260796
Idade: 58, PrÃªmio: 3927.0772873608726
Idade: 59, PrÃªmio: 1275.9549180959368
Idade: 48, PrÃªmio: 549.6832778099972
Idade: 63, PrÃªmio: 1511.9848054105532
Idade: 51, PrÃªmio: 444.1558039460032
Idade: 74, PrÃªmio: 2175.8324807941544
Idade: 62, PrÃªmio: 2158.438067733314
Idade: 48, PrÃªmio: 3734.067958686067
Idade: 70, PrÃªmio: 1409.7665466695491
Idade: 18, PrÃªmio: 1611.4214100964743
Idade: 41, PrÃªmio: 1520.2305574320128
Idade: 19, PrÃªmio: 2358.897708279181
Idade: 41, PrÃªmio: 1767.4458481057973
Idade: 64, PrÃªmio: 1837.132500324685
Idade: 55, PrÃªmio: 1099.1610370949438
Idade: 79, PrÃªmio: 1306.3513992120315
Idade: 39, PrÃªmio: 1812.9487847829785
Idade: 62, PrÃªmio: 1972.7371419400117
Idade: 40, PrÃªmio: 1268.1821029343764
Idade: 51, PrÃªmio: 2551.45190755309
Idade: 47, PrÃªmio: 124.60497079087007
Idade: 61, PrÃªmio: 3766.4925806905712
Idade: 37, PrÃªmio: 1979.7616410098951
Idade: 31, PrÃªmio: 2601.873817437775
Idade: 41, PrÃªmio: 873.9070510937688
Idade: 29, PrÃªmio: 1230.7388820923525
Idade: 57, PrÃªmio: 706.6950939942201
Idade: 65, PrÃªmio: 1765.0564789772939
Idade: 63, PrÃªmio: 1329.0250224083973
Idade: 41, PrÃªmio: 1038.8336907726018
Idade: 70, PrÃªmio: 7133.956997975276
Idade: 78, PrÃªmio: 4510.572952750557
Idade: 19, PrÃªmio: 4316.26265081402
Idade: 38, PrÃªmio: 582.215495819904
Idade: 33, PrÃªmio: 764.2082943068464
Idade: 67, PrÃªmio: 735.8502393992588
Idade: 57, PrÃªmio: 2306.209458287654
Idade: 35, PrÃªmio: 786.0792396272717
Idade: 30, PrÃªmio: 6044.359597718714
Idade: 20, PrÃªmio: 990.8878502475427
Idade: 66, PrÃªmio: 665.0263681776338
Idade: 52, PrÃªmio: 1110.0160465954687
Idade: 31, PrÃªmio: 2995.4042534386344
Idade: 60, PrÃªmio: 337.7548387922922
Idade: 24, PrÃªmio: 1464.6055303016383
Idade: 32, PrÃªmio: 1710.7147297789109
Idade: 75, PrÃªmio: 1240.8839233078204
Idade: 49, PrÃªmio: 3243.1681410955757
Idade: 78, PrÃªmio: 903.0082676674467
Idade: 44, PrÃªmio: 1336.1576407179557
Idade: 30, PrÃªmio: 1731.7045761020509
Idade: 70, PrÃªmio: 1087.0990370183686
Idade: 41, PrÃªmio: 8026.338251075926
Idade: 25, PrÃªmio: 2197.952833142238
Idade: 58, PrÃªmio: 6634.9779325794225
Idade: 50, PrÃªmio: 3393.576599917838
Idade: 56, PrÃªmio: 2297.6795042474414
Idade: 66, PrÃªmio: 1343.0672536071495
Idade: 24, PrÃªmio: 271.4486816779132
Idade: 69, PrÃªmio: 4391.86497147593
Idade: 22, PrÃªmio: 821.8698795180168
Idade: 44, PrÃªmio: 2360.724570158201
Idade: 29, PrÃªmio: 4516.442867980148
Idade: 71, PrÃªmio: 1087.2308955198148
Idade: 26, PrÃªmio: 2544.115634769388
Idade: 64, PrÃªmio: 492.09598918304283
Idade: 22, PrÃªmio: 2085.7424443236305
Idade: 36, PrÃªmio: 1804.2714742666387
Idade: 21, PrÃªmio: 3286.725724415016
Idade: 33, PrÃªmio: 2676.2539270319944
Idade: 77, PrÃªmio: 1880.716341123481
Idade: 53, PrÃªmio: 1419.37803591298
Idade: 27, PrÃªmio: 1843.1462093550192
Idade: 47, PrÃªmio: 2847.7391220657387
Idade: 36, PrÃªmio: 6142.318644619901
Idade: 42, PrÃªmio: 1343.1958561580652
Idade: 59, PrÃªmio: 2091.19147449274
Idade: 23, PrÃªmio: 1736.5330230613672
Idade: 23, PrÃªmio: 1761.0509093215792
Idade: 33, PrÃªmio: 2401.200129901314
Idade: 77, PrÃªmio: 2891.9809326887575
Idade: 73, PrÃªmio: 1683.0355804289397
Idade: 37, PrÃªmio: 438.5039279165352
Idade: 52, PrÃªmio: 5675.121923506807
Idade: 50, PrÃªmio: 798.0600881573207
Idade: 74, PrÃªmio: 1410.3053865483785
Idade: 78, PrÃªmio: 1460.3291048592457
Idade: 45, PrÃªmio: 473.60899642661224
Idade: 29, PrÃªmio: 1848.5832949806224
Idade: 30, PrÃªmio: 1052.0184783365469
Idade: 66, PrÃªmio: 685.6866918905422
Idade: 70, PrÃªmio: 2173.584803178656
Idade: 39, PrÃªmio: 1818.4460486642438
Idade: 33, PrÃªmio: 1032.580478471904
Idade: 21, PrÃªmio: 1509.2701744838469
Idade: 40, PrÃªmio: 1873.7371163875325
Idade: 66, PrÃªmio: 784.7498576916722
Idade: 24, PrÃªmio: 4977.301328082725
Idade: 32, PrÃªmio: 1983.8528281900622
Idade: 46, PrÃªmio: 1574.1971772115826
Idade: 28, PrÃªmio: 2089.838816242576
Idade: 71, PrÃªmio: 566.3014283199898
Idade: 30, PrÃªmio: 1328.0799180341028
Idade: 34, PrÃªmio: 1186.300004818282
Idade: 36, PrÃªmio: 1183.2565951343422
Idade: 70, PrÃªmio: 1111.529329421331
Idade: 79, PrÃªmio: 4995.185104550185
Idade: 36, PrÃªmio: 2761.840047280388
Idade: 23, PrÃªmio: 3223.5855513939864
Idade: 60, PrÃªmio: 1148.0007187278438
Idade: 26, PrÃªmio: 3090.601044271086
Idade: 29, PrÃªmio: 2644.2562985080353
Idade: 66, PrÃªmio: 3814.00928899364
Idade: 34, PrÃªmio: 968.0533111301384
Idade: 78, PrÃªmio: 1237.1360134384024
Idade: 64, PrÃªmio: 435.1947058420437
Idade: 20, PrÃªmio: 1424.6604574181847
Idade: 62, PrÃªmio: 685.5924193617162
Idade: 76, PrÃªmio: 2737.812236406431
Idade: 35, PrÃªmio: 1723.2196715537277
Idade: 50, PrÃªmio: 4003.7875034910107
Idade: 44, PrÃªmio: 1138.7674592316512
Idade: 39, PrÃªmio: 1937.0503099047876
Idade: 45, PrÃªmio: 1394.343119961262
Idade: 54, PrÃªmio: 931.9784163031238
Idade: 18, PrÃªmio: 1055.9747183530123
Idade: 24, PrÃªmio: 2418.8569877333166
Idade: 75, PrÃªmio: 4658.439444545502
Idade: 59, PrÃªmio: 567.3743208315587
Idade: 69, PrÃªmio: 2701.6750963655645

In [44]:
idades_premios = base[['idades', 'premios']]
idades_premios

     idades      premios
0        58  2873.078718
1        71  2606.123705
2        33   839.817127
3        70   922.505137
4        38  1007.038732
..      ...          ...
995      70  1281.203814
996      21  2959.811180
997      62  1717.442196
998      26  3188.182856
999      74   911.179913

[1000 rows x 2 columns]

In [45]:
base.to_csv('dados.csv')

In [46]:
dados = read_csv('dados.csv', index_col='Unnamed: 0')
dados

      ids  idades sexos  estados_civis  sinistros      premios
0       1      58     F      Casado(a)          3  2873.078718
1       2      71     F      Casado(a)          2  2606.123705
2       3      33     M    Solteiro(a)          3   839.817127
3       4      70     M    Solteiro(a)          4   922.505137
4       5      38     F  Divorciado(a)          2  1007.038732
..    ...     ...   ...            ...        ...          ...
995   996      70     F    Solteiro(a)          1  1281.203814
996   997      21     M    Solteiro(a)          3  2959.811180
997   998      62     F      Casado(a)          2  1717.442196
998   999      26     F    Solteiro(a)          3  3188.182856
999  1000      74     F      Casado(a)          1   911.179913

[1000 rows x 6 columns]

In [47]:
def classificar_idade(idade):
    if idade >= 18 and idade <= 30:
        return 'Jovem'
    elif idade >= 31 and idade <= 45:
        return 'Adulto'
    else:
        return 'SÃªnior'

In [48]:
dados['Categoria'] = dados['idades'].apply(classificar_idade)
dados

      ids  idades sexos  estados_civis  sinistros      premios Categoria
0       1      58     F      Casado(a)          3  2873.078718    SÃªnior
1       2      71     F      Casado(a)          2  2606.123705    SÃªnior
2       3      33     M    Solteiro(a)          3   839.817127    Adulto
3       4      70     M    Solteiro(a)          4   922.505137    SÃªnior
4       5      38     F  Divorciado(a)          2  1007.038732    Adulto
..    ...     ...   ...            ...        ...          ...       ...
995   996      70     F    Solteiro(a)          1  1281.203814    SÃªnior
996   997      21     M    Solteiro(a)          3  2959.811180     Jovem
997   998      62     F      Casado(a)          2  1717.442196    SÃªnior
998   999      26     F    Solteiro(a)          3  3188.182856     Jovem
999  1000      74     F      Casado(a)          1   911.179913    SÃªnior

[1000 rows x 7 columns]

In [49]:
def calcular_desconto(pessoa):
    if pessoa['sinistros'] == 0:
        if pessoa['Categoria'] == 'Jovem':
            return pessoa['premios'] * 0.05
        elif pessoa['Categoria'] in ['Adulto', 'SÃªnior']:
            return pessoa['premios'] * 0.1
    return 0

In [54]:
dados['Desconto'] = dados.apply(calcular_desconto, axis=1)
dados

,ids,idades,sexos,estados_civis,sinistros,premios,Categoria,Desconto
0,1,58,F,Casado(a),3,2873.078718,SÃªnior,0.0
1,2,71,F,Casado(a),2,2606.123705,SÃªnior,0.0
2,3,33,M,Solteiro(a),3,839.817127,Adulto,0.0
3,4,70,M,Solteiro(a),4,922.505137,SÃªnior,0.0
4,5,38,F,Divorciado(a),2,1007.038732,Adulto,0.0
...,...,...,...,...,...,...,...,...
995,996,70,F,Solteiro(a),1,1281.203814,SÃªnior,0.0
996,997,21,M,Solteiro(a),3,2959.811180,Jovem,0.0
997,998,62,F,Casado(a),2,1717.442196,SÃªnior,0.0
998,999,26,F,Solteiro(a),3,3188.182856,Jovem,0.0
999,1000,74,F,Casado(a),1,911.179913,SÃªnior,0.0